version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-no-server-header
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge